server:
  port: 8081

spring:
  datasource:
    username: "postgres"
    password: "iconcile"
    url: "jdbc:postgresql://65.1.154.157:5432/test"
    driverClassName: "org.postgresql.Driver"
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format-sql: true
        ddl-auto: validate
        jdbc:
          lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace